import { Mission, UserProfile, Contact, CoachingAction, TrajectoryDataPoint, HabitEntry, MessageTemplate } from '../types';

// Default profile — Blake's real seed. Persisted to AsyncStorage on first run via Storage.loadProfile().
export const demoProfile: UserProfile = {
  id: 'blake-holley',
  email: 'blake.frontierlabs@gmail.com',
  full_name: 'Blake Holley',
  bio: 'IT & Automation engineer · Python developer · AI & systems builder. Targeting NOC, IT Support, Junior Sysadmin, and Automation Engineer roles in Denver/Boulder/Remote.',
  avatar_url: undefined,
  skills: ['Python', 'Network Administration', 'IT Support', 'System Administration', 'Automation', 'Linux', 'Git & GitHub', 'TypeScript', 'API Integration', 'Prompt Engineering'],
  north_star_goal: 'Break the $30k ceiling — land a $60–80k IT/automation role within 6–12 months. Relocate to Denver/Boulder.',
  archetypes: ['Builder', 'Strategist', 'Explorer'],
  risk_tolerance: 8,
  coach_mode: 'drill_sergeant',
  is_job_seeker: true,
  streak_count: 0,
  career_energy: 80,
  theme_primary: '#00F5FF',
  theme_accent: '#8A2BE2',
  theme_mode: 'dark',
  notification_prefs: {
    daily_brief: true,
    follow_up_reminders: true,
    streak_alerts: true,
    weekly_retro: true,
  },
  created_at: '2026-05-17T00:00:00Z',
  updated_at: '2026-05-17T00:00:00Z',
};

export const demoMissions: Mission[] = [
  {
    id: 'm1',
    user_id: 'demo-user-001',
    company: 'Stellar Dynamics',
    role: 'Senior Frontend Engineer',
    salary_min: 180000,
    salary_max: 220000,
    status: 'interviewing',
    description: 'Building next-gen dashboard for space logistics platform. React, TypeScript, WebGL.',
    location: 'San Francisco, CA (Hybrid)',
    url: 'https://stellardynamics.io/careers',
    notes: 'Great culture fit. CTO is ex-SpaceX. Round 2 scheduled for April 3.',
    applied_date: '2024-03-10',
    follow_up_date: '2024-04-03',
    readiness_score: 85,
    created_at: '2024-03-08T00:00:00Z',
    updated_at: '2024-03-26T00:00:00Z',
  },
  {
    id: 'm2',
    user_id: 'demo-user-001',
    company: 'Nebula Labs',
    role: 'Staff Engineer',
    salary_min: 200000,
    salary_max: 260000,
    status: 'applied',
    description: 'Leading mobile engineering team. React Native, iOS, Android.',
    location: 'Remote',
    notes: 'Applied via referral from Jake. Strong match for skills.',
    applied_date: '2024-03-22',
    follow_up_date: '2024-04-01',
    readiness_score: 72,
    created_at: '2024-03-20T00:00:00Z',
    updated_at: '2024-03-22T00:00:00Z',
  },
  {
    id: 'm3',
    user_id: 'demo-user-001',
    company: 'Warp Drive Inc.',
    role: 'Engineering Manager',
    salary_min: 220000,
    salary_max: 280000,
    status: 'offer',
    description: 'Managing a team of 8 engineers building propulsion simulation software.',
    location: 'Austin, TX',
    notes: 'Offer: $245K base + equity. Need to respond by April 5.',
    applied_date: '2024-02-28',
    readiness_score: 95,
    created_at: '2024-02-25T00:00:00Z',
    updated_at: '2024-03-28T00:00:00Z',
  },
  {
    id: 'm4',
    user_id: 'demo-user-001',
    company: 'Quantum Forge',
    role: 'Principal Engineer',
    salary_min: 250000,
    salary_max: 300000,
    status: 'saved',
    description: 'Architecting distributed systems for quantum computing platform.',
    location: 'New York, NY',
    readiness_score: 45,
    created_at: '2024-03-25T00:00:00Z',
    updated_at: '2024-03-25T00:00:00Z',
  },
  {
    id: 'm5',
    user_id: 'demo-user-001',
    company: 'Cosmos AI',
    role: 'Senior Full-Stack Engineer',
    salary_min: 190000,
    salary_max: 230000,
    status: 'rejected',
    description: 'Building AI-powered developer tools.',
    location: 'Remote',
    notes: 'Rejected after final round. Feedback: wanted more ML experience.',
    applied_date: '2024-02-15',
    readiness_score: 60,
    created_at: '2024-02-10T00:00:00Z',
    updated_at: '2024-03-15T00:00:00Z',
  },
  {
    id: 'm6',
    user_id: 'demo-user-001',
    company: 'Photon Systems',
    role: 'Lead Frontend Architect',
    salary_min: 195000,
    salary_max: 240000,
    status: 'interviewing',
    description: 'Designing component systems and design tokens for enterprise SaaS.',
    location: 'Seattle, WA (Hybrid)',
    notes: 'Phone screen went well. Technical round next week.',
    applied_date: '2024-03-18',
    follow_up_date: '2024-04-02',
    readiness_score: 78,
    created_at: '2024-03-16T00:00:00Z',
    updated_at: '2024-03-25T00:00:00Z',
  },
];

export const demoContacts: Contact[] = [
  {
    id: 'c1',
    user_id: 'demo-user-001',
    name: 'Jake Torres',
    company: 'Nebula Labs',
    role: 'VP of Engineering',
    email: 'jake@nebulalabs.io',
    birthday: '1988-07-15',
    hobbies: ['Rock climbing', 'Board games'],
    how_we_met: 'React Conf 2023',
    last_interaction: '2024-03-20',
    notes: 'Referred me to Nebula Labs. Catch up monthly.',
    tags: ['referral', 'mentor', 'tech'],
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-03-20T00:00:00Z',
  },
  {
    id: 'c2',
    user_id: 'demo-user-001',
    name: 'Sarah Chen',
    company: 'Stellar Dynamics',
    role: 'CTO',
    email: 'sarah@stellardynamics.io',
    birthday: '1985-11-02',
    hobbies: ['Sailing', 'Photography'],
    how_we_met: 'LinkedIn cold outreach',
    last_interaction: '2024-03-26',
    notes: 'Interviewing with her team. Very responsive.',
    tags: ['interviewer', 'executive', 'tech'],
    created_at: '2024-03-05T00:00:00Z',
    updated_at: '2024-03-26T00:00:00Z',
  },
  {
    id: 'c3',
    user_id: 'demo-user-001',
    name: 'Marcus Williams',
    company: 'Warp Drive Inc.',
    role: 'Hiring Manager',
    email: 'marcus@warpdrive.com',
    how_we_met: 'Recruiter outreach',
    last_interaction: '2024-03-28',
    notes: 'Extended offer. Very enthusiastic about my background.',
    tags: ['recruiter', 'offer'],
    created_at: '2024-02-20T00:00:00Z',
    updated_at: '2024-03-28T00:00:00Z',
  },
  {
    id: 'c4',
    user_id: 'demo-user-001',
    name: 'Priya Patel',
    company: 'TechStars',
    role: 'Career Coach',
    email: 'priya@techstars.com',
    birthday: '1990-04-22',
    hobbies: ['Yoga', 'Podcasting'],
    how_we_met: 'Career coaching program',
    last_interaction: '2024-03-15',
    notes: 'Monthly coaching sessions. Great for interview prep.',
    tags: ['coach', 'mentor'],
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-03-15T00:00:00Z',
  },
  {
    id: 'c5',
    user_id: 'demo-user-001',
    name: 'David Kim',
    company: 'Photon Systems',
    role: 'Engineering Director',
    email: 'david@photonsys.com',
    how_we_met: 'Former colleague at Acme Corp',
    last_interaction: '2024-03-18',
    notes: 'Connected me with the hiring team at Photon.',
    tags: ['former-colleague', 'referral'],
    created_at: '2024-03-10T00:00:00Z',
    updated_at: '2024-03-18T00:00:00Z',
  },
];

export const demoCoachingActions: CoachingAction[] = [
  {
    id: 'a1',
    title: 'Follow up with Stellar Dynamics',
    description: 'Send thank-you note to Sarah Chen after Round 1 interview.',
    priority: 'high',
    completed: false,
    type: 'follow_up',
  },
  {
    id: 'a2',
    title: 'Prepare for Photon Systems technical round',
    description: 'Review system design patterns and component architecture.',
    priority: 'high',
    completed: false,
    type: 'apply',
  },
  {
    id: 'a3',
    title: 'Evaluate Warp Drive offer',
    description: 'Compare compensation, growth potential, and culture fit.',
    priority: 'medium',
    completed: false,
    type: 'apply',
  },
];

export const demoTrajectoryData: TrajectoryDataPoint[] = [
  { date: '2024-02-01', applications: 2, responses: 0, interviews: 0, energy: 65 },
  { date: '2024-02-08', applications: 4, responses: 1, interviews: 0, energy: 70 },
  { date: '2024-02-15', applications: 3, responses: 2, interviews: 1, energy: 75 },
  { date: '2024-02-22', applications: 5, responses: 2, interviews: 1, energy: 72 },
  { date: '2024-03-01', applications: 4, responses: 3, interviews: 2, energy: 80 },
  { date: '2024-03-08', applications: 3, responses: 2, interviews: 2, energy: 78 },
  { date: '2024-03-15', applications: 2, responses: 3, interviews: 3, energy: 85 },
  { date: '2024-03-22', applications: 3, responses: 2, interviews: 2, energy: 82 },
  { date: '2024-03-29', applications: 1, responses: 3, interviews: 2, energy: 88 },
];

export const demoHabits = [
  { id: 'h1', label: 'Apply to 1 role', icon: 'rocket-outline' },
  { id: 'h2', label: 'Network outreach', icon: 'people-outline' },
  { id: 'h3', label: 'Skill building (30 min)', icon: 'school-outline' },
  { id: 'h4', label: 'Update mission log', icon: 'document-text-outline' },
  { id: 'h5', label: 'Self-care check-in', icon: 'heart-outline' },
];

export const messageTemplates: MessageTemplate[] = [
  {
    id: 'mt1',
    type: 'birthday',
    label: 'Birthday Wishes',
    template: 'Happy birthday, {{name}}! Hope you have an amazing day. Would love to catch up soon — let me know when you have time for a quick coffee chat.',
  },
  {
    id: 'mt2',
    type: 'congrats',
    label: 'Congratulations',
    template: 'Congrats on {{achievement}}, {{name}}! That\'s a huge milestone. Really happy for you. Let\'s celebrate over coffee sometime.',
  },
  {
    id: 'mt3',
    type: 'check_in',
    label: 'Check-In',
    template: 'Hey {{name}}, it\'s been a while! How are things going at {{company}}? I\'d love to hear what you\'ve been working on. Free for a quick call this week?',
  },
  {
    id: 'mt4',
    type: 'restart_thread',
    label: 'Restart Thread',
    template: 'Hi {{name}}, I know it\'s been a while since we connected. I\'ve been {{update}} and thought of you. Would love to reconnect — are you free for a chat?',
  },
  {
    id: 'mt5',
    type: 'thank_you',
    label: 'Thank You',
    template: 'Hi {{name}}, I wanted to thank you for {{reason}}. It really meant a lot and made a difference. Looking forward to staying in touch.',
  },
];
